### ISSUE TITLE
HiREPS code request

### ISSUE THREAD

**Issue by navid-hoseini** [RicardoDominguez/PyCREPS#15]
Thanks for sharing your code on CREPS. Do you have any source code for HiREPS?

**Comment by RicardoDominguez** [comment]
I do not. However it would be a great addition if you'd like to contribute.

**Comment by navid-hoseini** [comment]
Hi,

Actually I am trying to implement HiREPS in Matlab. But I haven't been able to get my code working yet. If I succeed, I will definitely share my code. Thanks for your reply.

Best, Navid
